name: Deploy

on:
  workflow_run:
    workflows: ["PR"]
    types: 
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Log context
        uses: actions/github-script@v5
        with:
          script:
            console.log(JSON.stringify(context, null, 2))
    # if: >
    #   ${{ github.event_name == 'push' &&
    #   github.event.workflow_run.conclusion == 'success' }}