name: PR

on: [pull_request, push]

jobs:
  build:
    name: PR check
    runs-on: ubuntu-latest
    steps:
      - name: Chekout Code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.6"
